# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P2LLmLZ6NnydGm8hTdgkw_ofDXbK9tNG
"""

print("hello")